version: '3.8'
services:
  frontend:
    container_name: Frontend
    build:
      context: ../app/frontend
      dockerfile: ../../docker/frontend/Dockerfile
    volumes:
      - ../app/frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NUXT_PUBLIC_API_URL=/api
