version: '3.8'

services:
  reverse-proxy:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend

  frontend:
    build:
      context: ../app/frontend
      dockerfile: ../../docker/frontend/Dockerfile
    volumes:
      - ../app/frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NUXT_PUBLIC_API_URL=/api


  backend:
    build:
      context: ../app/backend
      dockerfile: ../../docker/backend/Dockerfile
    expose:
      - "80"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=${POSTGRES_DB}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: