version: '3.8'
services:
  backend:
    container_name: Backend
    build:
      context: ../app/backend
      dockerfile: ../../docker/backend/Dockerfile
    expose:
      - "80"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=${POSTGRES_DB}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - db
