version: '3.8'
services:
  reverse-proxy:
    container_name: Reverse-Proxy
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
