name: Database
services:
  database:
    build: ./database
    container_name: ${DB_HOST}
    expose:
      - "3306"
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_PASS}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: