name: App
services:
  app:
    build: ./app/
    container_name: Web
    env_file: ".env"
    ports:
      - "80:80"
    volumes:
      - type: bind
        source: ../app
        target: /var/www/html